### PR TITLE
add code snippet and sidenav to documentation page

### PR DESCRIPTION
**Pull request by Maianki**
# Added Code snippet and sidenav to documentation Page.

## Screenshots of changes made:
Desktop View
Mobile View

## Live preview Link :
https://docs-page-preview.netlify.app/

### Thanks for reviewing ☺

### CODE REVIEW

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me.

**Review by vrinda-mahajan — APPROVED** [review]
LGTM👍

**Comment by vrinda-mahajan** [comment]
.The footer is overlapping the sidebar. Please look into it.

**Comment by Maianki** [comment]
> .The footer is overlapping the sidebar. Please look into it.

Thanks for pointing that out will fix it.

**Pull request merged**
