### PR TITLE
add landing page

### PR DESCRIPTION
**Pull request by Maianki**
# Added Landing Page for component Library:

## Desktop View

Landing Page Desktop View

## Mobile View
Landing Page Mobile View

## Live Link :
https://landing-preview.netlify.app/

### Thanks for reviewing my PR 😊.

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
UI looks amazing man . Keep on doing the good work

**Comment by Maianki** [comment]
> UI looks amazing man . Keep on doing the good work

Thanks Akshat.

**Review by vrinda-mahajan — APPROVED** [review]
LGTM👍

**Comment by Maianki** [comment]
> LGTM👍

Thanks for reviewing.

**Pull request merged**
