### PR TITLE
add cards component

### PR DESCRIPTION
**Pull request by Maianki**
# Added different versions of card component:
## Cards with badges
Cards with badge
## Horizontal card
Horizontal cards

## Cards with dismiss
Cards with dismiss

## Cards with overlay
Cards with overlay

## Text only cards
Text only cards

## Card with shadow
Cards with shadow

### CODE REVIEW

**Review by vrx29 — APPROVED** [review]
Looks good to me. Your code is clean.

**Comment by Maianki** [comment]
> Looks good to me. Your code is clean.

Thanks for reviewing 😊

**Review by foolhardy21 — APPROVED** [review]
clean and tidy.👍🏾

**Comment by Maianki** [comment]
> clean and tidy.👍🏾

Thanks 😊

**Review by sainath7878 — COMMENTED** [review]
Looks good to me

**Pull request merged**
