### PR TITLE
Simplified grid

### PR DESCRIPTION
**Pull request by Maianki**
# Added two items and three items simplified grids

## Two Items in a grid
Screenshot (573)
Screenshot (574)

## Three Items in a grid
Screenshot (575)
Screenshot (576)

### Live link
https://amazing-darwin-f016a1.netlify.app/docs.html

### CODE REVIEW

**Review by hsnice16 — APPROVED** [review]

**Comment by hsnice16** [comment]
Nice work, bro.

**Review by vrinda-mahajan — APPROVED** [review]
Looks good to merge.

**Comment by Maianki** [comment]
> Nice work, bro.

Thanks for reviewing.

**Comment by Maianki** [comment]
> Looks good to merge.

Thanks for reviewing

**Pull request merged**
