### PR TITLE
feat: add responsive navbar with hamburger

### PR DESCRIPTION
**Pull request by Maianki**
### On larger viewport
Screenshot (618)

### On smaller viewport
Screenshot (619)

### CODE REVIEW

**Comment by shruthipatil11** [comment]
Great work!.
Good usage of aria-label.
 
Suggestions: You can implement the below suggestions going forward

1.when  class="list-inline" is applied is on every li tag. It can be accessed directly ul. classname li {}, rather than writing classname on every li tags . 

2.Please provide brief image description in alt tag.

`<a class="navbar-brand" href="#">
            
    </a>      `
           

Looks good to merge.

**Review by shruthipatil11 — APPROVED** [review]

**Comment by Maianki** [comment]
> Great work!. Suggestion: when class="list-inline" is applied is on every li tag. It can be accessed directly ul. classname li {}, rather than writing classname on every li tags . Looks good to merge.

Thanks for the suggestion.

**Review by TejasShekar — APPROVED** [review]
Component working as described. So, looks good to merge.

**Comment by Maianki** [comment]
> Component working as described. So, looks good to merge.

Thanks for reviewing

**Pull request merged**
