### PR TITLE
add image and input components

### PR DESCRIPTION
**Pull request by Maianki**
# Added responsive image and different variants of input.
## Responsive and round images
responsive and round images

## Textboxes
Textboxes

##Checkbox, radio and select inputs
checkboxes and radio buttons

## Default form validation
Default validation

## Custom form validation
custom form validation
 
### Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by Developers-codz — APPROVED** [review]
Looks good to me !

**Comment by Maianki** [comment]
> Looks good to me !

Thanks for reviewing 😊

**Comment by hsnice16** [comment]
Nice work, Ankit. Proper spacing in CSS and HTML code, proper naming, Clean UI. Great.

**Review by hsnice16 — APPROVED** [review]

**Review by samyukthasudhakar — APPROVED** [review]
Looks amazing. The code is well structure and neat. LGTM :D

**Comment by Maianki** [comment]
> Nice work, Ankit. Proper spacing in CSS and HTML code, proper naming, Clean UI. Great.

Thanks for reviewing Himanshu. 😊

**Comment by Maianki** [comment]
> Looks amazing. The code is well structure and neat. LGTM :D

Thanks for reviewing 😊

**Pull request merged**
