### PR TITLE
add modal

### PR DESCRIPTION
**Pull request by Maianki**
# Added modal 
Modal Component

## Live Link
https://heuristic-roentgen-868727.netlify.app/

### CODE REVIEW

**Review by mikesch803 — APPROVED** [review]

**Review by vishal804 — APPROVED** [review]

**Comment by vishal804** [comment]
looks Good

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me!!

**Comment by Maianki** [comment]
> looks Good

Thanks for reviewing.

**Comment by Maianki** [comment]
> Looks good to me!!

Thanks for reviewing

**Pull request merged**
