### PR TITLE
Get Started text color fixed

### PR DESCRIPTION
**Pull request by Manoharvuradi**
class is not added to "Get Started", Now it is fixed.

### CODE REVIEW

**Comment by Maianki** [comment]
Can you please add before and after screenshots of the changes that you have done in the description. Also please comment on the ticket related to this PR. And add the issue number in the description.

**Comment by Manoharvuradi** [comment]
@Maianki
issue number is #17
Single class is added to the "Get Started". After adding the "component-subheading" changes appeared.
 
before
Screenshot from 2022-09-18 23-51-30

After 
Screenshot from 2022-09-18 23-48-41

**Comment by Maianki** [comment]
@Manoharvuradi Thanks for raising the PR. Merging your PR.
 Few things that will help you going forward :
- Comment on the issue first that you want to work on and wait for the maintainer to assign it to you.
- Once assigned only then start working on it and raise the PR.
- Provide a description in your PR about the issue you worked on and link the issue number.

**Comment by Manoharvuradi** [comment]
Thanks for the information.
But, This is my first PR.

**Comment by Maianki** [comment]
> Thanks for the information. But, This is my first PR.

No problem. Your changes have been merged to dev. Congrats on your first contribution.🎉

**Pull request merged**
