### PR TITLE
add rating and snackbar

### PR DESCRIPTION
**Pull request by Maianki**
# Added rating and snackbar

## Rating 
Screenshot (562)

## Snackbar
Screenshot (563)

### Live Link
https://elated-volhard-d5f31e.netlify.app/

### Thanks for reviewing 😊

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Nice work

**Review by samyukthasudhakar — APPROVED** [review]
Looks neat and well structured. Great work with the components 🔥

**Comment by Maianki** [comment]
> Nice work

Thanks

**Comment by Maianki** [comment]
> Looks neat and well structured. Great work with the components 🔥

Thank you

**Pull request merged**
