### PR TITLE
Dark mode and refactor

### PR DESCRIPTION
**Pull request by Maianki**
## Added dark mode
Screenshot (611)
Screenshot (610)

## Live link here
https://angry-albattani-4a12ba.netlify.app/

### Thanks for reviewing my PR

### CODE REVIEW

**Review by sainath7878 — APPROVED** [review]
Everything looks good, one suggestion is name your localStorage item as mode and values as dark and light.

**Review by TejasShekar — APPROVED** [review]
Looks good to merge

**Comment by Maianki** [comment]
> Everything looks good, one suggestion is name your localStorage item as mode and values as dark and light.

Thanks for reviewing. I am actually just toggling the dark-mode class that's why I have given names such as enableDarkMode and disableDarkMode.

**Review by aryanandarnav13 — COMMENTED** [review]
Looks Good

**Pull request merged**
