### PR TITLE
add navigation

### PR DESCRIPTION
**Pull request by Maianki**
# Added navigation 
Navigation component

## Live Link:
https://xenodochial-lalande-82343e.netlify.app/

### CODE REVIEW

**Review by ArjunJunna — APPROVED** [review]
Can increase the size of icons by a bit. Rest everything is clean.

**Comment by Maianki** [comment]
> Can increase the size of icons by a bit. Rest everything is clean.

Thanks for reviewing.

**Review by vrinda-mahajan — APPROVED** [review]
Good to merge.

**Comment by Maianki** [comment]
> Good to merge.

Thanks for reviewing.

**Pull request merged**
